### ISSUE TITLE
Adjustment problem

### ISSUE THREAD

**Issue by Bezik1** [CallMeTwitch/Neural-Network-Zoo#2]
Hi I studied your code and I tried to adjust it to some data_set in order to create chat bot, but I have issues with adjusting this code to the normal data sets not only single text. Do you have idea how to do it?

**Comment by CallMeTwitch** [comment]
I'm going to assume you're using the LSTM code.

If you want to use more than one sample text, you can just update the "chars" variable to contain the characters from all texts before creating the "char_to_idx" and "idx_to_char" dictionaries, and create a "train_X" and "train_y" variable for each text and train on the concatenation of these. For example:

```
data = 'Insert first text here'.lower()
data2 = 'Insert second text here'.lower()

chars = set(data + data2)
char_size = len(chars)

char_to_idx = {c:i for i, c in enumerate(chars)}
idx_to_char = {i:c for i, c in enumerate(chars)}

data_X, data_y = data[:-1], data[1:]
data2_X, data2_y = data2[:-1], data2[1:]

train_X, train_y = data_X + data2_X, data_y + data2_y
```

From there the code should be the same. However, I must caution you: this code was written for educational purposes, so people could understand what was happening under the hood- this was not made for large projects like chatbots. Keras, Tensorflow, Jax or PyTorch are much better equipped for that kind of project, they will train much faster and be more accurate, and most likely less buggy. If you still want to proceed with NumPy, the code above should work. Best of luck.
